### ISSUE TITLE
unrecognized command:  phoneticenc not defined by phoneticenc.ado

### ISSUE THREAD

**Issue by AndrewCast** [wbuchanan/StataStringUtilities#1]
```
phoneticenc make, caverphone1(cav1) caverphone2(cav2) col(kolner) dms(daitch) dblm(dblmeta) metap(metaphone) nys(nysiis) beiderm(bmencode) matchrating(mrati
> ng)
unrecognized command:  phoneticenc not defined by phoneticenc.ado
r(199);
```

I'm following to `Phonetic String Encoding` example. When I tried to run the above command, I am returned an error. Thanks.

**Comment by wbuchanan** [comment]
@AndrewCast if you use the files from the gh-pages branch it should take care of that.  It may take me a bit to get a chance to handle merging the branches.
